### ISSUE TITLE
How to train only Single GPU ?

### ISSUE THREAD

**Issue by tysnow2022** [CityU-AIM-Group/NLTE#1]

**Comment by xinyuliu-jeffrey** [comment]
@tysnow2022 You may execute 
'''
python tools/train_net.py --config-file "path/to/config/file.yaml" DATASETS.ANNOTATIONS Noisy_Annotations_per_$NOISYRATE 
'''
directly.

**Comment by tysnow2022** [comment]
Thank you for the Quick reply.I started the training but after some time when it starts the evaluation the 'CUDA OUT OF MEMORY' error is thrown i try reducing the batch size even down to 2 and the learning  rate to 0.00025 but still the error persists. I tried to evaluate it using the provided pretrained model but the same error happens even for evaluation using the pretrained model.  what is the possible solution please?

**Comment by xinyuliu-jeffrey** [comment]
@tysnow2022 The training requires bs at least 2. Could you provide your GPU memory info by nvidia-smi in the console? It may due to your limited GPU memory.

**Comment by xinyuliu-jeffrey** [comment]
@tysnow2022 For evaluation it may require not that large batch size. You can set TEST.IMS_PER_BATCH = 1 during testing.

**Comment by tysnow2022** [comment]
Here is my GPU information. the evaluation started after some minute of training (after around 10 minute) because of that it unable to finish the training. is it evaluate at each step or at the end of the training process?
![info](https://user-images.githubusercontent.com/24326843/168302101-a17679b9-f55e-4cb9-8642-125612072a42.PNG)

**Comment by xinyuliu-jeffrey** [comment]
@tysnow2022 The GPU memory is only 8G thus is not that sufficient. To disable evaluation during training, you may comment https://github.com/CityU-AIM-Group/NLTE/blob/6c67f8148395e9170a97d6d89e585d14cd14d1f0/maskrcnn_benchmark/engine/trainer.py#L238-L273 and https://github.com/CityU-AIM-Group/NLTE/blob/6c67f8148395e9170a97d6d89e585d14cd14d1f0/maskrcnn_benchmark/engine/trainer.py#L275. 

Another possible solution to save GPU memory is to comment https://github.com/CityU-AIM-Group/NLTE/blob/6c67f8148395e9170a97d6d89e585d14cd14d1f0/maskrcnn_benchmark/modeling/roi_heads/box_head/roi_box_predictors.py#L48-L73 (disable inner domain aggregation). It may affect the performance a little bit, but will save quite a lot GPU memory.

**Comment by tysnow2022** [comment]
Ok thank you The evaluation works but I think it's not the correct result I use the pretrained model provided and it shows the these results
![pretra](https://user-images.githubusercontent.com/24326843/168306417-e1838310-0800-4407-9985-5a916c33aa54.PNG)

**Comment by xinyuliu-jeffrey** [comment]
@tysnow2022 The evaluated results seem fine at my side
![image](https://user-images.githubusercontent.com/59467295/168309071-ab633427-7de9-4bf8-85ae-d28a328fc727.png)

Please follow the following instructions to perform evaluation:
1. Download the trained model and put it under NLTE/
2. Under the dir NLTE/ , Run: python tools/train_net.py --config-file ./configs/da_faster_rcnn/e2e_da_c2f.yaml MODEL.WEIGHT model_best_0.45.pth OUTPUT_DIR ./test_trained_cityscapes SOLVER.TEST_ONLY True

**Comment by tysnow2022** [comment]
I was using test_net.py and other e2e_da_faster_rcnn_R_50_C4_cityscapes_to_foggy_cityscapes.yaml file. it works now.

**Comment by tysnow2022** [comment]
Can you please check this error i encountered it during training process?
![error1](https://user-images.githubusercontent.com/24326843/168323550-700c524e-25c8-4132-bef5-cb62a8a9a679.png)

**Comment by xinyuliu-jeffrey** [comment]
@tysnow2022 Sorry for my late reply. I have checked the issue and found that a previous version of categoryaware_da_heads.py has been updated. I have updated a new version. You may clone the current repo again and run it, or follow my latest commit to modify your code.

**Comment by tysnow2022** [comment]
Oh thank you for the update let me check it now .

**Comment by tysnow2022** [comment]
when i restart the training  it starts from the beginning How can i  add a checkpoint or can you update it please?

**Comment by xinyuliu-jeffrey** [comment]
@tysnow2022 You cannot resume training without saving a checkpoint. You can add 
'''
        if iteration % 5000== 0:
            save_model_only(model2, os.path.join(cfg.OUTPUT_DIR, "model_{:07d}.pth".format(iteration)))
'''
before
https://github.com/CityU-AIM-Group/NLTE/blob/0e9083abea1dbc7818f63a2e9004c02d836044ed/maskrcnn_benchmark/engine/trainer.py#L254

And use argument MODEL.WEIGHT $YOURCHECKPOINT when resuming training. I recommend you to refer to https://github.com/facebookresearch/maskrcnn-benchmark/blob/main/maskrcnn_benchmark/engine/trainer.py for more details about the training logic in maskrcnn-benchmark framework.

**Comment by tysnow2022** [comment]
Okay sorry for late reply i got it thanks.
